spring:
  application:
    name: executor

kafka:
  bootstrap-servers-config: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    prefer-ip-address: true


